"""v3 — Selectivity-estimation error fan chart.

ILLUSTRATIVE only at v0.1.0: per-bucket error envelopes are *synthetic*,
sampled from analytic distributions whose shape matches the expected
behaviour of each estimator. The figure source data will be replaced once
the OLAP harness (PostgreSQL EXPLAIN + DeepDB-style learned estimator) exists.

The three error fans are:
    - PostgreSQL histogram: degrades sharply at high selectivity ranges
      because multidimensional dependencies are lost in the 1-D marginals.
    - DeepDB-style learned estimator: roughly flat moderate error.
    - D₂-based (correlation-fractal-dimension): low error in the
      scaling region, larger error at the extreme tails of the workload.
"""
from __future__ import annotations

import numpy as np


def _synthetic_fan(
    n_buckets: int,
    mean_curve: np.ndarray,
    spread_curve: np.ndarray,
    seed: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return per-bucket median + IQR-style envelope from a deterministic seed.

    The envelope is purely illustrative; it is generated by sampling 200
    pseudo-replicates around ``mean_curve`` with per-bucket Gaussian noise
    proportional to ``spread_curve``, then summarizing as the 25/50/75
    percentiles. This is enough to render the fan chart shape we expect
    from each estimator class without claiming real measurements.
    """
    rng = np.random.default_rng(seed)
    n_rep = 200
    noise = rng.standard_normal((n_rep, n_buckets)) * spread_curve[None, :]
    samples = mean_curve[None, :] + noise
    q25 = np.quantile(samples, 0.25, axis=0)
    q50 = np.quantile(samples, 0.50, axis=0)
    q75 = np.quantile(samples, 0.75, axis=0)
    return q25, q50, q75


def render(st):
    """Streamlit render callable."""
    import plotly.graph_objects as go

    st.title("v3 — Selectivity estimation error fan")
    st.warning(
        "ILLUSTRATIVE: figure source data will be replaced once the OLAP "
        "harness exists (PostgreSQL EXPLAIN + DeepDB-equivalent learned "
        "cardinality estimator). The fan shapes below are synthetic and "
        "match each estimator's expected qualitative behaviour, not a "
        "real measurement."
    )

    st.markdown(
        "For a fixed multidimensional workload, each estimator produces a "
        "per-bucket selectivity estimate. We plot relative error along the "
        "workload range. The interesting visual question is *where* in the "
        "range each estimator's fan widens."
    )

    n_buckets = 40
    x = np.linspace(0.0, 1.0, n_buckets)

    # PostgreSQL histogram: low error at small selectivities, grows fast
    # at large selectivities where multidim joins lose marginal info.
    pg_mean = 0.05 + 0.6 * x**2
    pg_spread = 0.04 + 0.25 * x**2
    pg_q25, pg_q50, pg_q75 = _synthetic_fan(n_buckets, pg_mean, pg_spread, seed=11)

    # DeepDB-style: roughly flat moderate error band.
    dd_mean = 0.15 + 0.05 * np.cos(2 * np.pi * x)
    dd_spread = np.full_like(x, 0.06)
    dd_q25, dd_q50, dd_q75 = _synthetic_fan(n_buckets, dd_mean, dd_spread, seed=22)

    # D₂ estimator: low everywhere except mild bumps at the workload tails.
    d2_mean = 0.07 + 0.05 * (x - 0.5) ** 2 * 4
    d2_spread = 0.03 + 0.04 * (x - 0.5) ** 2 * 4
    d2_q25, d2_q50, d2_q75 = _synthetic_fan(n_buckets, d2_mean, d2_spread, seed=33)

    def _fan_traces(name: str, colour: str, q25, q50, q75, fill_rgba: str):
        return [
            go.Scatter(
                x=x, y=q75, mode="lines", line=dict(width=0),
                showlegend=False, hoverinfo="skip",
            ),
            go.Scatter(
                x=x, y=q25, mode="lines", line=dict(width=0),
                fill="tonexty", fillcolor=fill_rgba,
                name=f"{name} IQR",
            ),
            go.Scatter(
                x=x, y=q50, mode="lines",
                line=dict(color=colour, width=2), name=f"{name} median",
            ),
        ]

    fig = go.Figure()
    for trace in _fan_traces(
        "PostgreSQL", "#C62828", pg_q25, pg_q50, pg_q75, "rgba(198,40,40,0.18)",
    ):
        fig.add_trace(trace)
    for trace in _fan_traces(
        "DeepDB-style", "#2E7D32", dd_q25, dd_q50, dd_q75, "rgba(46,125,50,0.18)",
    ):
        fig.add_trace(trace)
    for trace in _fan_traces(
        "D₂-based", "#4A6FA5", d2_q25, d2_q50, d2_q75, "rgba(74,111,165,0.22)",
    ):
        fig.add_trace(trace)

    fig.update_layout(
        height=520,
        margin=dict(l=0, r=0, t=10, b=0),
        xaxis_title="workload range (normalized)",
        yaxis_title="relative selectivity error",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0),
    )
    st.plotly_chart(fig, use_container_width=True)

    st.caption(
        "Expected shape at v0.2+: PostgreSQL's fan widens where the workload "
        "queries hit correlated columns; the D₂-based estimator stays narrow "
        "in the fractal scaling region and degrades only at the workload's "
        "extreme tails. The headline H4 figure of the master plan."
    )
